### ISSUE TITLE
discord api reponds with `DiscordAPIError: Invalid Form Body`

### ISSUE THREAD

**Issue by adrian-goe** [Yes-Theory-Fam/yesbot-ts#563]
This was in the logs and my needs further investigation:

```txt
/usr/src/app/node_modules/discord.js/src/rest/RequestHandler.js:298
      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: Invalid Form Body
message_reference: Unknown message
    at RequestHandler.execute (/usr/src/app/node_modules/discord.js/src/rest/RequestHandler.js:298:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/usr/src/app/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at async TextChannel.send (/usr/src/app/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:171:15)
    at async changeHostOnDemand (/usr/src/app/build/programs/voice-on-demand.js:235:5)
    at async voiceOnDemand (/usr/src/app/build/programs/voice-on-demand.js:49:13)
    at async routeMessage (/usr/src/app/build/events/message.js:29:17)
    at async message (/usr/src/app/build/events/message.js:9:9)
    at async Client.<anonymous> (/usr/src/app/build/index.js:45:5) {
  method: 'post',
  path: '/channels/698544577677754428/messages',
  code: 50035,
  httpStatus: 400,
  requestData: {
    json: {
      content: 'I transfered ownership of your room to <@ -- some id -- >!',
      tts: false,
      nonce: undefined,
      embeds: undefined,
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: 0,
      message_reference: { message_id: ' -- some id -- ', fail_if_not_exists: true },
      attachments: undefined,
      sticker_ids: undefined
    },
    files: []
  }
}
error Command failed with exit code 1.
```

**Comment by geisterfurz007** [comment]
Has not occured in ages
